### ISSUE TITLE
Exception on startup program

### ISSUE THREAD

**Issue by christopherdecoster** [SQLPlayer/SCD-Merge-Wizard#20]
ScdMergeWizard Error Report
-----------------------------

Application Version: 4.3.0.0
Report date: 7/12/2022 11:07:30
OS: Microsoft Windows NT 6.2.9200.0 [Microsoft Windows 11 Pro]
Processors count: 8
Installed .NET versions:
  -> CDF SP0
  -> v2.0.50727 SP2
  -> v3.0 SP2
  -> v3.5 SP1
  -> v4 SP0
  -> v4.0 SP0

========== MESSAGE: 1 ==========

Message:
String was not recognized as a valid DateTime.

Source:
mscorlib

Stack Trace:
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at ScdMergeWizard.Recent.RecentFile.FromFileString(String fileString)
   at ScdMergeWizard.Recent.RecentFilesManager.Read()
   at ScdMergeWizard.MainForm.loadRecentFiles()
   at ScdMergeWizard.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by NowinskiK** [comment]
Sorry, not enough information to recreate the issue.
